### ISSUE TITLE
agregar caso para notificar creacion de una OC

### ISSUE THREAD

**Issue by says33** [TechMindsMX/modulusuno-v3#126]

**Comment by Atites** [comment]
Que tengo que probar aquí?

**Comment by temocpalma** [comment]
Que llegue el correo al rep legal cuando se crea una orden de compra

**Comment by Atites** [comment]
Le llega cuando ya fue pagada. Antes solo llega al Autorizador, y despuñes el Tesorero. Osea que al crearse no esta llegando. Y están llegando dos correos a todos.
