### ISSUE TITLE
Aplicar comisión de pago a las órdenes de compras y de retiro

### ISSUE THREAD

**Issue by temocpalma** [TechMindsMX/modulusuno-v3#149]

**Comment by Atites** [comment]
Esto lo veo funcionando en stage ok, sin embargo esta pendiente ver que el monto de las comisiones e ivas se vayan a una cuenta específica. Este ya se mueve a prdo y se cierra y se abre otro?

**Comment by temocpalma** [comment]
Sí, ya está en la tarjeta 183 en Backlog

**Comment by Atites** [comment]
ok esto va a cambiar por lo que vimos ayer. slds
