### ISSUE TITLE
Al dar de alta clientes/proveedores permitir agregar domicilio de tipo fiscal

### ISSUE THREAD

**Issue by temocpalma** [TechMindsMX/modulusuno-v3#156]

**Comment by temocpalma** [comment]
Se validó el alta de direcciones de una empresa también para que sólo se pueda registrar una sola dirección de tipo fiscal

**Comment by Atites** [comment]
ya puedo dar de alta dirección fiscal. pero al dar clic sobre la direccion para querer editar algo manda error.

Mensaje: No signature of method: com.modulus.uno.AddressService.getAddressTypesForEditCompanyAddress() is applicable for argument types: (com.modulus.uno.Address, java.lang.Long) values: [KM 2.5 CARRETERA A TEQUISQUIAPAN #SN C.P 76802 Querétaro, 7] Possible solutions: getAddressTypesForEditCompanyAddress(com.modulus.uno.Address, java.lang.String)

URL: /address/edit/27

**Comment by temocpalma** [comment]
No pude replicar el error
