### ISSUE TITLE
Validar caracteres del campo descripción de los items de una orden de venta para que no acepte caracteres extraños

### ISSUE THREAD

**Issue by temocpalma** [TechMindsMX/modulusuno-v3#158]

**Comment by Atites** [comment]
Que son caracteres extraños. No me acepta ñ, pero si acentos, )(/%$, no acepta &, etc... Que es lo que no debe aceptar?

**Comment by temocpalma** [comment]
Sólo permite números, letras incluyendo Ñ, espacios, y los siguientes signos: + - . # $ % * ( ) ; :
Cualquier otro caracter que se intente escribir no se podrá
