### ISSUE TITLE
Agregar descuento a las órdenes de venta

### ISSUE THREAD

**Issue by temocpalma** [TechMindsMX/modulusuno-v3#172]

**Comment by Atites** [comment]
ya lo revise y esta jalando mal el proceso. busco a temoc para verlo por teléfono

**Comment by Atites** [comment]
ok, ya se reviso y esta calculando bine. solo se va a modificar el pdf quitando dos columnas de los IVAs

**Comment by Atites** [comment]
Listo. aparece ya la leyenda y el cálculo es correcto.
