### ISSUE TITLE
Agregar campo alias stp a las empresas

### ISSUE THREAD

**Issue by temocpalma** [TechMindsMX/modulusuno-v3#173]

**Comment by Atites** [comment]
entre a dar de alta una nueva empresa para ver si me pide el alias de STP y puse 345 empleados y marco error, así como 700,000,000 y marco error. Hay que modificar estos límites para que acepte cualquier número, es simplemente informativo. Quizá bloquearlos en 9,999,999,999

El error lo marca en Inglés. Hay que modificarlo a español

En ningún lado como usuario corporativo o rep legal vi un campo de alias de STP. ese solo sale con el usuario Master.

**Comment by Atites** [comment]
Esto esta resuelto en el 174

**Comment by temocpalma** [comment]
Se creó la tarjeta #191 para hacer el ajuste de los mensajes de validación
