### ISSUE TITLE
Ajustar webservice de orden de venta con los nuevos campos de método de pago, moneda y tipo de cambio

### ISSUE THREAD

**Issue by temocpalma** [TechMindsMX/modulusuno-v3#193]

**Comment by Atites** [comment]
Ok, pero no pedí un campo con el tipo de cambio. Ese hay que quitarlo. Solo que especifique si es dólares o pesos.

**Comment by neodevelop** [comment]
No se pone la moneda en USD y se pone el tipo de cambio?
o como sería?
